### PR TITLE
feature: Delete cloudinary images (#1)

### PR DESCRIPTION
**Pull request by arsen1c**
This commit attempts to add the ability to delete images on Cloudinary via `api/cloudinary` endpoint. I have added 
- A utility function to delete cloudinary image using the cloudinary sdk.
- A `DELETE` endpoint that will use the utility function to delete images from coludinary.

### Screenshots
**Success**
image

**Fail**
image

### CODE REVIEW

**Review by harshmangalam — APPROVED** [review]
Approved

**Comment by arsen1c** [comment]
Hey, @harshmangalam if you don't mind then can you add a hacktoberfest accepted label on this PR?

**Comment by harshmangalam** [comment]
Yes adding i was busy to add this changes to production and applying secrets key in heroku hence taken some time

**Comment by arsen1c** [comment]
That's completely fine. Thanks, I appreciate that.

**Pull request merged**
